### ISSUE TITLE
Does rss.xml link discovery work?

### ISSUE THREAD

**Issue by kmike** [scrapinghub/autoextract-spiders#16]
See https://github.com/scrapinghub/autoextract-spiders/blob/e43932778fbd2a60d4c45ef99f0b9780c90a2283/autoextract_spiders/spiders/autoextract_article.py#L92 - it seems this code iterates over characters in href, not over hrefs

**Comment by croqaz** [comment]
Good catch! Fixed in https://github.com/scrapinghub/autoextract-spiders/pull/20
